image: eicweb.phy.anl.gov:4567/containers/eic_container/jug_dev:testing

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "webide"'
    - if: '$CI_COMMIT_BRANCH == "master"'


default:
  before_script:
    - mkdir -p images && mkdir -p doc/
  tags:
    - phy
  artifacts:
    paths:
      - images/
      - doc/
    reports:
      dotenv: juggler.env

stages:
  - config
  - build
  - deploy


env:
  stage: config 
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  script:
    - |
      if [[ "x${CI_PIPELINE_SOURCE}" == "xmerge_request_event"  || "$CI_COMMIT_BRANCH" == "master" ]]; then
        export EIC_DATA_MODEL_VERSION="${CI_COMMIT_REF_NAME}"
        echo "EIC_DATA_MODEL_VERSION = ${EIC_DATA_MODEL_VERSION}"
        echo "EIC_DATA_MODEL_VERSION=$CI_COMMIT_REF_NAME" >> juggler.env
      fi
    - mkdir -p "/scratch/${CI_PROJECT_NAME}_${CI_PIPELINE_ID}" && cp juggler.env /scratch/${CI_PROJECT_NAME}_${CI_PIPELINE_ID}/juggler.env && printenv > /scratch/${CI_PROJECT_NAME}_${CI_PIPELINE_ID}/env.out
  artifacts:
    reports:
      dotenv: juggler.env

compile:
  stage: build
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  needs:
    - ["env"]
  script:
    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make -j20 && make install


checks:juggler:
  stage: deploy
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  variables:
    JUGGLER_EICD_VERSION: "$EIC_DATA_MODEL_VERSION"
  trigger:
    project: EIC/juggler
    strategy: depend

      #benchmarks:physics:
      #  stage: deploy
      #  rules:
      #    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
      #  needs:
      #    - ["compile"]
      #  trigger:
      #    project: EIC/benchmarks/physics_benchmarks
      #    strategy: depend

gen_doxygen_src:
  stage: build
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install 
  artifacts:
    paths:
    - build/src
    - build/eicd

pages:
  image: eicweb.phy.anl.gov:4567/containers/eic_container/alpine
  stage: deploy
  needs: ['gen_doxygen_src']
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
    - cd build && cp -r ../docs/* . && doxygen Doxyfile  && cd ..
    - mkdir -p public && cp -r build/docs/html/* public/.
    #    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make doc_doxygen && cd ..
    #- cp -r build/doxygen_output/html public
  artifacts:
    paths:
    - public
