image: eicweb.phy.anl.gov:4567/containers/eic_container/eic:latest

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make -j20 && make install

gen_doxygen_src:
  stage: build
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install 
  artifacts:
    paths:
    - build/src
    - build/eicd

pages:
  image: eicweb.phy.anl.gov:4567/containers/eic_container/alpine
  stage: deploy
  needs: ['gen_doxygen_src']
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
    - cd build && cp -r ../docs/* . && doxygen Doxyfile  && cd ..
    - mkdir -p public && cp -r build/docs/html/* public/.
    #    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make doc_doxygen && cd ..
    #- cp -r build/doxygen_output/html public
  artifacts:
    paths:
    - public
