image: eicweb.phy.anl.gov:4567/containers/eic_container/eic:latest

stages:
  - build
  - deploy

    #compile:
    #  stage: build
    #  tags:
    #    - sodium
    #  script:
    #    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make -j10 && make install
    #  artifacts:
    #    paths:
    #    - build/doxygen_output

gen_doxygen_src:
  stage: build
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install 
  artifacts:
    paths:
    - build/src
    - build/eicd

pages:
  image: eicweb.phy.anl.gov:4567/containers/eic_container/alpine
  stage: deploy
  needs: ['gen_doxygen_src']
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
    - cd build && mkdir -p doxygen_output && doxygen ../docs/Doxyfile  && cd ..
    - mkdir -p public && cp -r build/doxygen_output/html/* public/.
    #    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make doc_doxygen && cd ..
    #- cp -r build/doxygen_output/html public
  artifacts:
    paths:
    - public
