name: linux-lcg

on:
  push:
    branches:
      - master

jobs:
  build-lcg-docs:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-ubuntu2004-gcc9-opt"]
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          PREFIX=${PWD}/install
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          cmake --build build -- install
          cmake --build build -- docs
    - uses: actions/upload-artifact@v3
      with:
        name: build-lcg-docs
        path: build/docs/html/
        if-no-files-found: error
